### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by rbbri** [rbbri/acebook-gracebook#24]
Only allow logged in users past the index page

**Comment by Caitlin-cooling** [comment]
Ed: If you are doing it yourself, before filters/filter actions. Callbacks that hook into the sequence of events when a request is sent to a controller. Check if someone is signed in.

**Comment by Caitlin-cooling** [comment]
We have: 
- Protected the post controller
- Don't need to protect the session controller

Blocked on:
- Protecting user profile pages

**Comment by rbbri** [comment]
Seed test db or delete strategy using database_cleaner?
