### ISSUE TITLE
Update post has an issue with wrong flash message showing

### ISSUE THREAD

**Issue by IrinaSTA** [rbbri/acebook-gracebook#47]

**Comment by IrinaSTA** [comment]
In test environment, when I sign up, create new post and then go to edit it, i see flash message "You can only edit your own posts". I am then allowed to edit it. I shouldn't see the flash message, unless I am someone else.

**Comment by Caitlin-cooling** [comment]
I don't think this is still an issue is it @IrinaSTA ?
